project:
  type: book
  output-dir: docs

book:
  title: "Learners Paradigm"
  author: "Vaibhav Upadhyay"
  date: "24/05/2025"

  sidebar:
    style: docked
    background: light

  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
    - part: "__init__"
      chapters:
        - chapters_dir/chapters/01-basics.qmd
        - chapters_dir/chapters/02-pointers.qmd
    - part: "2_storing_data_elements"
      chapters:
        - chapters_dir/2_storing_data_elements/Array.qmd
        - chapters_dir/2_storing_data_elements/Matrix.qmd
    - part: "Scratching the Surface"
      chapters:
        - chapters_dir/scratching_the_surface/intro.qmd
    - part: "Design"
      chapters:
        - chapters_dir/Design/intro.qmd
bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    code-tools: true
    highlight-style: github
  pdf:
    documentclass: scrreprt
    toc: true
    toc-depth: 3
    number-sections: true
    colorlinks: true

execute:
  freeze: auto

